### ISSUE TITLE
Add Feature: Player Pushes Next Turn in Order

### ISSUE THREAD

**Issue by agjwilson** [shdwjk/Roll20API#15]
Would be a really nice feature for players to push button to move to the next turn.

Also, how do you reset the turn order. Mine is on Turn Order 57.

**Comment by bgbarcus** [comment]
Select the turn marker token that floats behind character tokens on their turn.  There are macros connected with the token for toggling whether announcement cards are displayed in the chat, and one to reset the turn order.

The chat cards have an "EoT" button on the bottom right corner that can be clicked to pass the turn.

**Comment by agjwilson** [comment]
I am using version = '1.3.3',

I do not see any macros, or EoT buttons. 

However I can click the token behind the players character tokens. :-D

The command for resetting the Turn order is 
`!tm reset`

**Comment by shdwjk** [comment]
@bgbarcus is using my secret version 2, which isn't quite finished.  I'm actually in the process of adding the eot button and some other things to version 1 right now, should be pushed later tonight.  =D

**Comment by agjwilson** [comment]
Well that's awesome ! I am just adding final touches to Vault of the Dracolich. Again. New improved version. So this feature would be such a bonus for this and my other Ravenloft game on a Sunday :-)

**Comment by shdwjk** [comment]
Just testing said bonus right now... =D

**Comment by shdwjk** [comment]
I've just released the version that has this and other fixes:  https://app.roll20.net/forum/permalink/3963829/
